# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: takataok <takataok@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/10 15:33:01 by takataok          #+#    #+#              #
#    Updated: 2021/04/13 10:58:11 by takataok         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS = ft_bzero.c ft_isascii.c ft_memccpy.c ft_memcpy.c ft_strchr.c ft_strlen.c ft_strrchr.c \
ft_isalnum.c ft_isdigit.c ft_memchr.c ft_memmove.c ft_strlcat.c ft_strncmp.c ft_tolower.c \
ft_atoi.c ft_isalpha.c ft_isprint.c ft_memcmp.c ft_memset.c ft_strlcpy.c ft_strnstr.c ft_toupper.c \
ft_calloc.c ft_strdup.c ft_substr.c ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c \
ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c

BSRCS = ft_lstadd_front.c ft_lstnew.c ft_lstsize.c ft_lstlast.c ft_lstadd_back.c\
 ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c\

ALL_SRCS = $(SRCS)

OBJS = ${ALL_SRCS:.c=.o}

BOBJS = ${BSRCS:.c=.o}

NAME = libft.a

HEADER_FILES = libft.h

bonus: ${OBJS} ${BOBJS}
	ar rcs $(NAME) ${OBJS} ${BOBJS}

$(NAME): ${OBJS}
	ar rcs $(NAME) ${OBJS}

%.o: %.c ${HEADER_FILES}
	gcc -Wall -Wextra -Werror -c $< -o ${<:.c=.o}

all: bonus

clean:
	rm -f ${OBJS} ${BOBJS}

fclean:
	rm -f ${OBJS} ${BOBJS} ${NAME}

re:	fclean all
